name: Deploy React Vite App to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  S3_BUCKET_NAME: web-student-dams
  CLOUDFRONT_DISTRIBUTION_ID: E24XAO9VUI2QUO

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ env.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
